import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={` antialiased bg-gray-100 gap-3`}>
        <Header />
        <div className="mt-20 mb-2 h-[100vh]">
        {children}

        </div>
        <div className="bottom-0">

        <Footer/>
        </div>

      </body>
    </html>
  );
}
